name: CICD pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  Test:
    runs-on: ubuntu-latest

    steps:
      - name: Git Clone
        uses: actions/checkout@v2

      - name: install the node
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      
      - name: install packages
        runs: npm install 

      - name: Run the Test
        runs: npm run test




  Deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout the home directory
        run : |
          cd /home/ubuntu/CICD-OSTAD
          git pull 
          pm2 status
          pm2 restart all


          
