name: CICD Pipeline

on:
  push:
    branches:
      -  main

  pull_request:
    branches:
      -  main



jobs:

  print_the_file:
    runs-on : ubuntu-latest

    steps:
      - name: Git Clone
        uses: actions/checkout@v2

      - name: Read the File  
        run:  cat hello.txt







